const quizInfo = [
  {
    level: 2,
    answer: "디지털 전환",
    exampleL: "디지털 전환",
    exampleR: "사이버 폭력",
    quiz_para: "000 00은 기존의 전통적인 방식을 디지털 기술을 활용하여 새롭게 바꾸는 것을 의미한다.",
    answer_word: "디지털 전환",
    answer_para: "은 기존의 전통적인 방식을 디지털 기술을 활용하여 새롭게 바꾸는 것이다.",
  },
  {
    level: 2,
    answer: "리걸테크",
    exampleL: "인간관계 축소",
    exampleR: "리걸테크",
    quiz_para: "디지털 기술이 주는 긍정적인 영향 한 가지를 선택하세요.",
    answer_word: "디지털 기술의 긍정적인 영향",
    answer_para:
      "으로는 개인 맞춤형 건강 관리 서비스 제공, 교육 접근성 향상, 리걸테크의 도입, 가상 현실에서 문화유산 체험, 스마트 그리드 등이 있다.",
  },
  {
    level: 3,
    answer: "스마트 그리드",
    exampleL: "디지털 문화재",
    exampleR: "스마트 그리드",
    quiz_para:
      "OOO OOO를 활용하면 전력 사용량을 예측하고<br/> 수요를 조절하여 전력 공급의 안전성과<br/> 에너지 효율성을 높일 수 있다.",
    answer_word: "스마트 그리드",
    answer_para: "는 전력 사용량을 예측하고 수요를 조사하여 전력 공급의 안전성과 에너지 효율성을 높일 수 있다.",
  },
  {
    level: 1,
    answer: "X",
    exampleL: "O",
    exampleR: "X",
    quiz_para: "외부 침입으로부터 정보를 보호하는 직업은<br/> 빅데이터 분석가이다.",
    answer_word: "사이버 보안 전문가",
    answer_para: "는 외부 침입으로부터 정보를 보호한다.",
  },
  {
    level: 2,
    answer: "핀테크",
    exampleL: "핀테크",
    exampleR: "NFT",
    quiz_para: "OOO는 모바일 결제, 송금, 개인 자산 관리, 크라우드펀딩 등 정보 기술을 기반으로 한 금융 서비스를 말한다.",
    answer_word: "핀테크",
    answer_para: "는 모바일 결제, 송금, 개인 자산 관리, 크라우드펀딩 등 정보 기술을 기반으로 한 금융 서비스이다.",
  },
  {
    level: 1,
    answer: "워크넷",
    exampleL: "워크넷",
    exampleR: "코랩",
    quiz_para: "진로 설계와 관련된 웹사이트 한 가지를 선택하세요.",
    answer_word: "워크넷",
    answer_para: "에는 취업과 진로 설계를 위한 정보가 있다.",
  },
  {
    level: 3,
    answer: "개인 정보",
    exampleL: "가명 정보",
    exampleR: "개인 정보",
    quiz_para: "OO OO는 살아 있는 개인에 관한 정보로서,<br/> 직접·간접 식별 정보가 있다.",
    answer_word: "개인 정보",
    answer_para: "는 살아 있는 개인에 관한 정보로서, 직접·간접 식별 정보가 있다.",
  },
  {
    level: 1,
    answer: "O",
    exampleL: "O",
    exampleR: "X",
    quiz_para: "정보를 안전하게 보호하기 위해 공용 컴퓨터를 이용한 후에는 반드시 로그아웃을 해야 한다.",
    answer_word: "정보를 안전하게 보호",
    answer_para: "하기 위해 공용 컴퓨터를 이용한 후에는 반드시 로그아웃을 해야 한다.",
  },
  {
    level: 3,
    answer: "디도스 공격",
    exampleL: "디도스 공격",
    exampleR: "접근 제어",
    quiz_para: "정보 보안에 실패했을 때, 발생할 수 있는 사이버 공격<br/> 피해 사례 한 가지를 선택하세요.",
    answer_word: "정보 보안에 실패했을 때, ",
    answer_para: "디도스 공격을 받을 수 있다.",
  },
  {
    level: 2,
    answer: "정보 공급자",
    exampleL: "정보 사용자",
    exampleR: "정보 공급자",
    quiz_para: "OO OOO는 제공받은 정보를 목적에 맞게<br/> 사용 후 삭제해야 한다.",
    answer_word: "정보 공급자",
    answer_para: "는 제공받은 정보를 목적에 맞게 사용한 후 삭제해야 한다.",
  },
];
